// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkPnIBY_pm7Hje5ES-v8Zq4ODNReBcjeo',
    appId: '1:735929071770:web:061389658b1824ec828723',
    messagingSenderId: '735929071770',
    projectId: 'zelow-d4440',
    authDomain: 'zelow-d4440.firebaseapp.com',
    storageBucket: 'zelow-d4440.firebasestorage.app',
    measurementId: 'G-MYR76QN1YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqO_9v0GyOG7762HR3p8lpf1kdL0T4mnU',
    appId: '1:735929071770:android:8c5d8e5d3e44305d828723',
    messagingSenderId: '735929071770',
    projectId: 'zelow-d4440',
    storageBucket: 'zelow-d4440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKuuKwkQ2RjvDRe4iCWWIWK_jZEH6xsYk',
    appId: '1:735929071770:ios:986f08045451dbdd828723',
    messagingSenderId: '735929071770',
    projectId: 'zelow-d4440',
    storageBucket: 'zelow-d4440.firebasestorage.app',
    iosClientId: '735929071770-sm0uapnatthmatao9qr0qmfiasurrlso.apps.googleusercontent.com',
    iosBundleId: 'com.example.zelow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKuuKwkQ2RjvDRe4iCWWIWK_jZEH6xsYk',
    appId: '1:735929071770:ios:986f08045451dbdd828723',
    messagingSenderId: '735929071770',
    projectId: 'zelow-d4440',
    storageBucket: 'zelow-d4440.firebasestorage.app',
    iosClientId: '735929071770-sm0uapnatthmatao9qr0qmfiasurrlso.apps.googleusercontent.com',
    iosBundleId: 'com.example.zelow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkPnIBY_pm7Hje5ES-v8Zq4ODNReBcjeo',
    appId: '1:735929071770:web:1bb253863d9d2c27828723',
    messagingSenderId: '735929071770',
    projectId: 'zelow-d4440',
    authDomain: 'zelow-d4440.firebaseapp.com',
    storageBucket: 'zelow-d4440.firebasestorage.app',
    measurementId: 'G-RVH8DLCX67',
  );
}
